language: node_js
node_js:
- '10'
script:
- npm run build
- npm run test
deploy:
  provider: npm
  on:
    tags: true
    repo: joernb/redux-prefabs-status
  email:
    secure: JpFWXPVrDkQZetmYpOKP2kz8JkPQrU9k6Od2/oOUd9BcnM/wrbY+/iT9Gy3Vcoz0LIqJpDJNbf/+KtRxfcSuybIYnZTFwQzTIjebqRNbd48nUMeZ/Rj9zFTYapSzz95/6n6AE+ia/NZ12cmNGSPE4LeMf/dg1y8/L3IUaXzWpmQxZEa/Xu8/+g9Oso1eIdPUKAH1yGk2dbenyS8zjw7RzFN35mXQPtAjRP9Wqe9qpLqSVhio4elulG2Yv1JSwLUzwHthyeKqOf97TIswS9IsXNnFYSkohq1XcKf2JuT1iX4lk9eC54sM4XdV3sOIawX7fjhl04OSKtU2tylKMWrsOm8XB9D6uVSsJQPTDYIGvD3mbGgVf684BYZNrUjvF1fAhB8ITl/WJaoIjUz8rire5CjZYTm8o9UBtD/rcNCe5un0llzgNlnE/BVth4rJEg/YC07GQqtwDnySmbBXBV4Yk7/gAEDpTl+L1T5OWaQuFGH67Q3QShKBeOZ0PEkrmMFnxmzJXF5ROfYnUjYsENPMsOZ93bC6HlIPEH7Gvnpz+nYnTz3hn/MLkAj8QHUZdetozsZbOBtOLPEVcXeL3gahw+Di/1G3cAG3yxtuvYlsemuou+G+HXpZGuViInnAiIEx4VJwT2jdFvl0+N21wZiUB0kZ1+pdi9i9atJZ1OxzrvM=
  api_key:
    secure: II+EvLBO8t6kyHeAFtH4Huc3CIm/gRs6+GEp4I9GbTvMaD0a7ZPiCyqZiPeLBwxcWpj9FL9O3INSXNWok/pVtQS7MsVFojsZf7QGeGrh10Llk8zF5beifXnUAlTVNaRgKgqBZJGJRhO87CWiIXRsycgigyG3bRuZJ3/P1qu24tK0gYWgjHYBolwImSn5CMLDasnfElGpMK0zQlkaHd2PF1UbACQTpbob7iHBU2RXvKadIN6KYxI5aGUNg8fwH7mj4UXiiH9wU83F7FYh3ZPK2YDgGZ8gugWFhU1wajDzlmKhEmVt0XakqpalpvvDKiE6RvA+96XiUZPqnfLIT4X08MHMzHKaSXlqNgTXJy+WGdvMcjHkV1/KFFiAisk/AiN7QzR0hum1KcTWyoEWyPX84nPC7vJICFPnfrMUEo/Cf3bpteOgInWX2QZjNaypxPtu1qh8jkqiwzZkEKHY1UIJGEBpilMJ+7mt4kGF54ByKzhJLGoXkYUdbsp1TRbCr8Tp5UwGnLDQXVxNCzl9Y+qyV3sdL8cjTJz8RrSqRWk0zVLpcSqlUpKN3VbQSH5CATH8qh0nigY4EDrszlirrjS4VeGPK6zSFwtIw5EcJoGXheor3ms0Twx9abgijvG02KD3yI6zZgDA9d3LSFczJL3N0wIlAT+Ed+hwqobLllnaWb4=
